sudo: false
language: python

python:
- 2.7
- 3.4
- 3.5
- &latest_py3 3.6

env: TOXENV=python

jobs:
  fast_finish: true
  include:
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      password:
        secure: LZwSEE+UMTtwPsRF7Bdfz9pPa6bGnvSqIUEuKxJ4eqwguP6HhsVGRkg6pj6WVyz4+zqOwgBtF8nu6Ul1I9MlOYjhOeI/1BXHSW4AuuFc8GFNEI0O/22dpbaXKl3Va2iVbb0np5iVw8tMlnJDLe9zjEeuPgk/y0j9+x8x81iw0nM=
      distributions: dists
      skip_cleanup: true

install:
  - "pip install tox"

script:
  - tox --develop --skip-missing-interpreters
