# Travis CI configuration ~ travis-ci.org
language: generic
dist: bionic
sudo: required

before_install:
  - sudo apt update

install:
  - sudo apt install -y make python-dev python3-dev tox

script:
  - make tox flags="-- --verbose"
